"""Question-independent memory and evidence-grounded question answering."""

PERCEPTION = """Build an emotional memory of the supplied audiovisual window. You do not receive any benchmark question or reference answer.
Use only these media and the preceding memory. Identify visible people from appearance, voice and grounded dialogue; never identify actors from outside knowledge. Reuse supplied P IDs only when supported. Give new people local IDs such as new_1. Unknown names must be null. The cast descriptions are hypotheses, not proof.
Separate observable cues (face, gesture, words, vocal tone, listener reactions) from inferred emotion. Capture mixed feelings and different emotional targets separately. Do not equate emotion target with its cause. Record observable intensity rather than arbitrary numerical ratings. Do not infer continuity across unseen gaps.
All spans use ABSOLUTE VIDEO SECONDS, within the supplied media range. The core interval owns new records; padding supplies context only. Emit only events overlapping the core. Capture each distinct occurrence; use continues_event ONLY if this is the same ongoing occurrence as a supplied earlier event, not a repeated similar action. Existing events may be linked by temporal, causal, changes_to, or coexists_with edges ONLY with evidence; temporal order alone does not establish causation.
Return one JSON object with entities, observations, events, relations, corrections. Required schema:
entities: [{id: local or existing P ID, name: string|null, description: visual/voice identity description}]
observations: [{id: local O ID, subject: entity ID, span:[start,end], cue: concrete observed words/behavior/tone, modality: visual|audio|subtitle|multimodal}]
events: [{id: local ID such as new_event_1 (distinct from existing E IDs), span:[start,end], summary: concrete occurrence, observation_ids:[local O IDs], continues_event: existing E ID|null, states:[{subject:entity ID, target: what this feeling concerns, emotion: open emotion description, intensity: observed manifestations, evidence_ids:[local O IDs], uncertainty: limitations, appraisal: evidence-grounded interpretation or null}]}]
relations: [{source: local or existing event ID, target: local or existing event ID, type: temporal|causal|changes_to|coexists_with, evidence_ids:[local O IDs]}]
corrections: [] unless corrections are explicitly enabled. If later evidence corrects the interpretation of an EARLIER same-time state, use {state_id:existing S ID, expected_version:integer, emotion:string, uncertainty:string, evidence_ids:[local O IDs], reason:string}. Do not use correction for a real later emotional change. Never silently erase an earlier state or invent psychological motives. Empty arrays are allowed when there is no evidence. Keep observations detailed enough to later answer questions about emotional developments, causes, intensity comparisons and distinct repeated occurrences."""

PLANNER = """Plan evidence retrieval for an emotion question about a video. You receive only the question and a cast index, never reference annotations. Return JSON:
{mode: trajectory|comparison|count|causal|local, entity_terms:[names/descriptions], target_terms:[events/topics/emotions], query_terms:[short lexical retrieval terms], time_range:[start,end]|null}.
Trajectory, comparison, count and multi-event causal questions need coverage across the entire question scope, not just the most similar moment. Resolve pronouns cautiously. time_range is a restriction explicitly in the question, not an invented guess. Keep all terms in the question language, adding useful synonyms only."""

ANSWER = """Answer this video-emotion question using the supplied memory and any inspected media. Do not rely on knowledge of the show or story outside the evidence. Distinguish observed cues from uncertain interpretations. Ground each statement in the correct person, emotional target and time. For trajectories, cover the necessary stages in order, including reversals and concurrent feelings; avoid compressing away a stage. For causes, include all supported necessary factors, without inventing motives. For comparisons, check the relevant candidate moments; for counts, distinguish unique occurrences from repeated observations of the same event. Navigation edges are not causal evidence.
Return JSON {answer: nonempty final answer in the question's language, evidence_ids:[event/observation IDs], uncertainty:short factual evidence limitations, inspect:[{start:number,end:number,question:neutral evidence question}]}.
If a missing audiovisual observation could materially change the answer, you may request a bounded inspect interval from the allowed budget. Do not request to confirm a preferred hypothesis. Always include your best current answer; if no more inspection budget remains, inspect must be empty. The final answer should directly satisfy the question, with enough concrete detail for completeness. Do not include internal node IDs, grading instructions or rubric guesses in answer."""

ANSWER_PROGRESSIVE = """Answer this video-emotion question using the currently disclosed evidence from a frozen event graph. The evidence is intentionally partial. Do not assume that an undisclosed event exists or does not exist, and do not rely on knowledge of the show outside the evidence. Distinguish observations from interpretations and ground claims in the correct person, emotional target and time.
The evidence may include a compact coverage_map. It is only a navigation index: event_hints are not sufficient evidence for a final claim, but their IDs may be used as anchors for a retrieve_more request. You may request another evidence page when the current evidence cannot establish a required time stage, comparison candidate, count, relation, or cause. Return JSON:
{answer: nonempty best answer in the question's language, evidence_ids:[event/observation IDs], uncertainty:short factual limitation, retrieve_more:[{anchor_ids:[event IDs], scope:same_target|same_subject|relations|time_range, direction:before|after|both, time_range:[start,end]|null, relation_types:[temporal|causal|changes_to|coexists_with], page_size:1..16, reason:string}], inspect:[]}.
Use retrieve_more only for a concrete missing evidence need, keep anchor_ids from the disclosed evidence, and do not repeat an already disclosed page. For trajectory, comparison, count, and multi-event causal questions, request at least one expansion unless the initial packet explicitly covers every required stage or candidate. If the evidence is sufficient, or no supported expansion is needed, set retrieve_more to []. Always include the best current answer even when requesting more evidence. Navigation edges are not causal evidence. Do not include internal node IDs in the answer text itself."""
